# Generated by Django 3.2.16 on 2022-12-01 20:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_schedule_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Agendamento'),
        ),
    ]
