# Generated by Django 3.2.16 on 2022-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º'), ('6', '6º'), ('7', '7º'), ('8', '8º'), ('9', '9º'), ('10', '10º')], max_length=2, verbose_name='Período'),
        ),
    ]
