# Generated by Django 3.2.16 on 2022-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(max_length=7, unique=True, verbose_name='Matrícula'),
        ),
    ]
