# Generated by Django 3.2.16 on 2022-12-09 05:06

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='res_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.teacher', verbose_name='Professor Responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
