# Generated by Django 3.2.16 on 2022-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_secretary_is_secretary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretary',
            name='is_secretary',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_secretary',
            field=models.BooleanField(default=True),
        ),
    ]
