# Generated by Django 3.2.16 on 2022-12-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
    ]
