# Generated by Django 3.2.16 on 2022-10-17 04:01

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contato')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Endereço')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('religion', models.CharField(blank=True, max_length=50, verbose_name='Religião')),
                ('profession', models.CharField(blank=True, max_length=50, verbose_name='Profissão')),
                ('marital_status', models.CharField(choices=[('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Separado'), ('4', 'Divorciado'), ('5', 'Viúvo')], max_length=1, verbose_name='Estado Civil')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('place_of_birth', models.CharField(blank=True, max_length=25, verbose_name='Naturalidade')),
                ('nationality', models.CharField(blank=True, max_length=25, verbose_name='Nacionalidade')),
                ('family_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Renda Familiar')),
                ('scholar_affiliation', models.CharField(blank=True, max_length=35, verbose_name='Instituição de Ensino')),
                ('treatment_bg', models.DateTimeField(blank=True, null=True, verbose_name='Início do Tratamento')),
                ('treatment_ed', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Tratamento')),
                ('discharged', models.BooleanField(blank=True, default=False, verbose_name='Recebeu Alta')),
                ('uni_affiliated', models.BooleanField(blank=True, default=False, verbose_name='Filiado a UNI')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
