# Generated by Django 3.2.16 on 2022-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_employee',
            field=models.BooleanField(blank=True, default=False, verbose_name='Funcionário'),
        ),
    ]
