# Generated by Django 3.2.16 on 2022-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome Completo'),
        ),
    ]
