# Generated by Django 3.2.16 on 2022-12-12 04:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20221209_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='N° Celular'),
        ),
    ]
