# Generated by Django 3.2.16 on 2022-12-12 05:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20221212_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
