# Generated by Django 3.2.16 on 2022-11-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '__first__'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='nome',
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Arquivos'),
        ),
    ]
