# Generated by Django 3.2.16 on 2022-11-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20221122_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Arquivos'),
        ),
        migrations.AlterField(
            model_name='report',
            name='relatorio',
            field=models.TextField(max_length=10000000, null=True, verbose_name='Relatório'),
        ),
    ]
