# Generated by Django 3.2.16 on 2022-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20221122_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='diagnostico',
            field=models.TextField(max_length=10000000, null=True, verbose_name='Diagnóstico'),
        ),
    ]
