# Generated by Django 3.2.16 on 2022-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Arquivos'),
        ),
    ]
