# Generated by Django 3.2.16 on 2022-11-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='diagnostico',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='relatorio',
            new_name='reports',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='titulo',
            new_name='title',
        ),
    ]
