# Generated by Django 3.2.16 on 2022-11-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_report_concluded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
    ]
