# Generated by Django 3.2.16 on 2022-11-30 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
    ]
