# Generated by Django 3.2.16 on 2022-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20221209_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='concluded',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reports',
            new_name='report',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
