# Generated by Django 3.2.16 on 2022-12-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_is_student'),
        ('report', '0016_auto_20221209_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='res_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.student', verbose_name='Paciente'),
        ),
    ]
